const COUNTIES = [
  "Alba",
  "Arad",
  "Argeș",
  "Bacău",
  "Bihor",
  "Bistrița-Năsăud",
  "Botoșani",
  "Brăila",
  "Brașov",
  "Buzău",
  "Călărași",
  "Caraș-Severin",
  "Cluj",
  "Constanța",
  "Covasna",
  "Dâmbovița",
  "Dolj",
  "Galați",
  "Giurgiu",
  "Gorj",
  "Harghita",
  "Hunedoara",
  "Ialomița",
  "Iași",
  "Ilfov",
  "Maramureș",
  "Mehedinți",
  "Mureș",
  "Neamț",
  "Olt",
  "Prahova",
  "Sălaj",
  "Satu Mare",
  "Sibiu",
  "Suceava",
  "Teleorman",
  "Timiș",
  "Tulcea",
  "Vâlcea",
  "Vaslui",
  "Vrancea",
  "București, Sectorul 1",
  "București, Sectorul 2",
  "București, Sectorul 3",
  "București, Sectorul 4",
  "București, Sectorul 5",
  "București, Sectorul 6",
];

const OBJECT_CATEGORY = [
  "Documente și carduri",
  "Electronice personale",
  "Chei și carduri de acces",
  "Haine și accesorii",
  "Animale de companie",
  "Obiecte de transport",
  "Jucǎrii și obiecte copii",
  "Altele",
];

export { COUNTIES, OBJECT_CATEGORY };
